# Generated by Django 4.1.7 on 2023-06-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managers',
            name='avatar_img_link',
        ),
    ]
