# Generated by Django 4.1.7 on 2023-06-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_categoty_food_manufacture_food_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
